import type { PricingPlan, BlogPost, Instructor, Retreat } from '@/types';

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: 'free',
    name: 'Seeker',
    price: { monthly: 0, yearly: 0 },
    description: 'Start your wellness journey with essential tools.',
    features: [
      'Access 20+ free yoga classes',
      'Basic meditation library',
      'Community forum access',
      'Weekly wellness tips',
      'Progress tracking (basic)',
    ],
  },
  {
    id: 'basic',
    name: 'Practitioner',
    price: { monthly: 19, yearly: 15 },
    description: 'Deepen your practice with guided programs.',
    features: [
      'Unlimited yoga class library',
      'Full meditation center access',
      'Live classes (4/month)',
      'AI wellness assistant',
      'Nutrition guidance',
      'Progress analytics',
      'Priority support',
    ],
  },
  {
    id: 'premium',
    name: 'Yogi',
    price: { monthly: 39, yearly: 29 },
    description: 'The complete wellness transformation toolkit.',
    highlighted: true,
    badge: 'Most Popular',
    features: [
      'Everything in Practitioner',
      'Unlimited live classes',
      '1-on-1 instructor sessions (2/month)',
      'Advanced AI wellness coach',
      'Retreat discounts (15%)',
      'Exclusive spiritual programs',
      'Downloadable content',
      'Family sharing (2 members)',
    ],
  },
  {
    id: 'elite',
    name: 'Master',
    price: { monthly: 79, yearly: 59 },
    description: 'For dedicated practitioners seeking mastery.',
    features: [
      'Everything in Yogi',
      '1-on-1 coaching (unlimited)',
      'Personal wellness consultant',
      'Retreat discounts (30%)',
      'Early access to new programs',
      'Certified instructor pathway',
      'White-glove onboarding',
      'Family sharing (5 members)',
    ],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'The Science Behind Morning Yoga: Why Your Body Craves It',
    excerpt: 'Discover how a consistent morning yoga practice rewires your nervous system, boosts cortisol naturally, and sets the tone for a mindful day.',
    author: 'Dr. Meera Patel',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    category: 'Yoga Science',
    readTime: '6 min read',
    publishedAt: 'May 20, 2026',
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    tags: ['Morning Yoga', 'Science', 'Wellness'],
  },
  {
    id: '2',
    title: 'Ayurvedic Principles for Modern Stress Management',
    excerpt: 'Ancient wisdom meets contemporary science. Learn how the three doshas guide personalized stress relief and emotional balance.',
    author: 'Arjun Sharma',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    category: 'Ayurveda',
    readTime: '8 min read',
    publishedAt: 'May 15, 2026',
    thumbnail: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&q=80',
    tags: ['Ayurveda', 'Stress', 'Lifestyle'],
  },
  {
    id: '3',
    title: '10 Meditation Techniques for Deep Sleep and Recovery',
    excerpt: 'Insomnia affects millions. These evidence-backed meditation methods activate the parasympathetic system for restorative sleep.',
    author: 'Priya Nair',
    authorAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    category: 'Meditation',
    readTime: '5 min read',
    publishedAt: 'May 10, 2026',
    thumbnail: 'https://images.unsplash.com/photo-1515023115689-589c33041d3c?w=800&q=80',
    tags: ['Sleep', 'Meditation', 'Recovery'],
  },
  {
    id: '4',
    title: 'Choosing Your First Yoga Retreat: A Complete Guide',
    excerpt: 'From Bali to Rishikesh, the world\'s best retreat destinations explained. How to match a retreat to your current spiritual journey.',
    author: 'Kavya Reddy',
    authorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80',
    category: 'Retreats',
    readTime: '10 min read',
    publishedAt: 'May 5, 2026',
    thumbnail: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=800&q=80',
    tags: ['Retreat', 'Travel', 'Spirituality'],
  },
  {
    id: '5',
    title: 'Pranayama: The Breath Practices That Transform Your Mind',
    excerpt: 'Breath is the bridge between body and mind. Explore Nadi Shodhana, Kapalabhati, and Bhramari for mental clarity and calm.',
    author: 'Ravi Kumar',
    authorAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    category: 'Pranayama',
    readTime: '7 min read',
    publishedAt: 'April 28, 2026',
    thumbnail: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&q=80',
    tags: ['Pranayama', 'Breathwork', 'Mind'],
  },
  {
    id: '6',
    title: 'Nutrition for Yogis: Sattvic Diet Explained',
    excerpt: 'What you eat influences not just your body but your consciousness. The sattvic diet promotes purity, clarity, and spiritual growth.',
    author: 'Dr. Meera Patel',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    category: 'Nutrition',
    readTime: '9 min read',
    publishedAt: 'April 22, 2026',
    thumbnail: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    tags: ['Diet', 'Nutrition', 'Spirituality'],
  },
];

export const INSTRUCTORS: Instructor[] = [
  {
    id: '1',
    name: 'Ananya Krishnan',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
    specialty: ['Hatha Yoga', 'Meditation', 'Pranayama'],
    rating: 4.9,
    reviews: 842,
    experience: '12 years',
    price: 75,
    verified: true,
    bio: 'Certified RYT-500 instructor specializing in holistic Hatha yoga and mindfulness meditation. Based in Mysore, India.',
    classes: 156,
  },
  {
    id: '2',
    name: 'Vikram Nair',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    specialty: ['Ashtanga', 'Vinyasa', 'Breathwork'],
    rating: 4.8,
    reviews: 621,
    experience: '9 years',
    price: 65,
    verified: true,
    bio: 'Dynamic Ashtanga and Vinyasa flow teacher with a background in sports science and biomechanics.',
    classes: 203,
  },
  {
    id: '3',
    name: 'Serene Kapoor',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80',
    specialty: ['Yin Yoga', 'Sound Healing', 'Restorative'],
    rating: 4.9,
    reviews: 503,
    experience: '7 years',
    price: 60,
    verified: true,
    bio: 'Yin yoga and sound healing practitioner focused on deep relaxation and nervous system restoration.',
    classes: 89,
  },
  {
    id: '4',
    name: 'Rohan Das',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    specialty: ['Kundalini', 'Spiritual Yoga', 'Chakra Work'],
    rating: 4.7,
    reviews: 378,
    experience: '15 years',
    price: 90,
    verified: true,
    bio: 'Kundalini yoga teacher and spiritual guide with extensive training in India and certified by KRI.',
    classes: 312,
  },
];

export const RETREATS: Retreat[] = [
  {
    id: '1',
    title: 'Sacred Valley Yoga & Meditation Retreat',
    location: 'Rishikesh, India',
    dates: 'Jun 15–22, 2026',
    price: 1299,
    rating: 4.9,
    spots: 12,
    image: 'https://images.unsplash.com/photo-1593811167562-9cef47bfc4d7?w=600&q=80',
    instructor: 'Ananya Krishnan',
    highlights: ['Daily yoga sessions', 'Silent meditation', 'Ganges ceremony', 'Ayurvedic meals'],
  },
  {
    id: '2',
    title: 'Bali Sunrise Wellness Journey',
    location: 'Ubud, Bali',
    dates: 'Jul 8–15, 2026',
    price: 2199,
    rating: 4.8,
    spots: 8,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80',
    instructor: 'Serene Kapoor',
    highlights: ['Sunrise yoga', 'Temple visits', 'Spa treatments', 'Cooking class'],
  },
  {
    id: '3',
    title: 'Himalayan Spiritual Immersion',
    location: 'Dharamsala, India',
    dates: 'Aug 3–10, 2026',
    price: 999,
    rating: 4.9,
    spots: 15,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    instructor: 'Rohan Das',
    highlights: ['Mountain meditation', 'Kundalini sessions', 'Buddhist teachings', 'Trekking'],
  },
];

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Shreya Malhotra',
    role: 'Software Engineer, Bangalore',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&q=80',
    rating: 5,
    text: 'YogicTown transformed my chaotic work-from-home routine into a peaceful daily ritual. The AI wellness coach is genuinely helpful — it adjusted my practice when I mentioned feeling burnt out.',
  },
  {
    id: '2',
    name: 'Marcus Chen',
    role: 'Entrepreneur, Singapore',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    rating: 5,
    text: 'I tried three other platforms before YogicTown. The quality of instructors here is on another level. My Ashtanga practice improved dramatically in just 6 weeks.',
  },
  {
    id: '3',
    name: 'Elena Rodriguez',
    role: 'Teacher, Barcelona',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=80',
    rating: 5,
    text: 'The Bali retreat I booked through YogicTown was life-changing. The entire booking process was smooth and the community around it is so warm and supportive.',
  },
  {
    id: '4',
    name: 'Priya Iyer',
    role: 'Doctor, Mumbai',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    rating: 5,
    text: 'As a physician, I recommend YogicTown to my patients managing anxiety. The guided meditations and sleep programs are evidence-aligned and genuinely effective.',
  },
  {
    id: '5',
    name: 'James Mitchell',
    role: 'Architect, London',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=80',
    rating: 5,
    text: 'The community aspect is what keeps me coming back. Daily challenges, forums, and the spiritual circles create a sense of connection I have not found anywhere else.',
  },
  {
    id: '6',
    name: 'Aisha Patel',
    role: 'Nutritionist, Dubai',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&q=80',
    rating: 5,
    text: 'The nutrition module combined with yoga programs is remarkable. The Ayurvedic meal planning feature alone is worth the subscription price.',
  },
];

export const FAQ_ITEMS = [
  {
    q: 'What is YogicTown and who is it for?',
    a: 'YogicTown is a holistic wellness platform for anyone interested in yoga, meditation, spiritual living, and overall wellbeing. Whether you are a complete beginner or an advanced practitioner, we have programs, instructors, and resources for every level.',
  },
  {
    q: 'How does the AI Wellness Coach work?',
    a: 'Our AI Wellness Coach analyzes your wellness profile, goals, activity history, and feedback to generate personalized daily recommendations. It adapts over time and can answer questions about yoga, nutrition, meditation, and lifestyle habits.',
  },
  {
    q: 'Can I become an instructor on YogicTown?',
    a: 'Yes! Certified yoga instructors can apply through our Instructor Program. We verify credentials, provide tools to publish classes and schedule sessions, and support your growth with our platform\'s built-in audience and marketing tools.',
  },
  {
    q: 'What types of yoga classes are available?',
    a: 'We offer Hatha, Vinyasa, Ashtanga, Yin, Kundalini, Restorative, Power Yoga, Prenatal Yoga, and more. Classes range from 15-minute quick sessions to 90-minute deep practices across beginner, intermediate, and advanced levels.',
  },
  {
    q: 'Are the live classes recorded for later viewing?',
    a: 'Yes, all live classes are recorded and available in our Session Library within 24 hours. Premium and Yogi plan members get unlimited access to the full recording library, including past live sessions.',
  },
  {
    q: 'How do retreat bookings work?',
    a: 'Browse retreats from our vetted partners worldwide, view detailed itineraries, and book directly through YogicTown. We handle payment processing, and Yogi and Master plan members receive exclusive discounts. Cancellation policies vary by retreat.',
  },
  {
    q: 'Is my personal health data secure?',
    a: 'Absolutely. YogicTown is built with privacy-first architecture. We use end-to-end encryption for all health data, are GDPR compliant, and never share or sell personal wellness information to third parties.',
  },
  {
    q: 'Can I switch or cancel my subscription anytime?',
    a: 'Yes, you can upgrade, downgrade, or cancel your subscription at any time from your account settings. Annual plan refunds are prorated. Monthly plans renew each month and can be cancelled before the next billing cycle.',
  },
];
